### ISSUE TITLE
Does flow client or pipeline support dryrun mode?

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/FATE-Client#145]
Does flow client or pipeline support dryrun mode?

The flow client or pipeline submit the job, and the flow server only parse the dag without running them.

It's only for testing the dag or pipeline

**Comment by nemirorox** [comment]
We currently do not provide dry run option, nonetheless, here are some options to consider if: 

a.) dag is desired: you may use `get_dag` api of pipeline once pipeline object is compiled

b.) to verify if pipeline is valid/may run successfully: in general, if pipeline can be compiled, corresponding dag is runnable; however, to check if corresponding job can finish successfully, an actual run is need, as combinations of inputs/outputs/parameters will affect final result. List for inputs and outputs of each components may be found [here](https://github.com/FederatedAI/FATE/blob/master/doc/2.0/fate/components/README.md#algorithm-list). We also include explanations for ml parameters in [doc string](https://github.com/FederatedAI/FATE/blob/master/python/fate/components/components/coordinated_lr.py#L38).

Hope this helps!
